# Generated by Django 4.2.6 on 2023-12-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_model_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
