# Generated by Django 4.2.6 on 2023-12-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_model_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_model',
            name='image',
        ),
    ]
