# Generated by Django 4.2.6 on 2023-12-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_model_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/media/uploads/'),
        ),
    ]
